spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_usuario
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: global321

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generic-ddl: true
    hibernate:
      ddl-auto: create-drop

endpoint:
  msdatosusuarios:
    host: http://localhost
    port: 8090
    uri: /user

server:
  port: 8087
